ARG DOCKER_IMAGE=artifacts.developer.gov.bc.ca/docker-remote/instrumentisto/flutter:3.19


# To build locally, point to a local base image you've already built (see openshift/wps-api-base)
# e.g. : docker build --build-arg DOCKER_IMAGE=wps-api-base:my-tag .

FROM ${DOCKER_IMAGE}