// Let's try a nice fat font size - assuming people can't easily see things.
const double fontSize = 16;
const double labelFontSize = fontSize + 3;
const double defaultCC = 50;
const double defaultFFMC = 80;
const double defaultLatitude = 37;
const double defaultLongitude = -122;
const double minAltitude = 0;
const double maxAltitude = 3000;
const double minLongitude = -180;
const double maxLongitude = 180;
const double minLatitude = -90;
const double maxLatitude = 90;
const double defaultAltitude = 100;
const double minGFL = 0.1;
const double maxGFL = 1.0;
const double defaultGFL = 0.35;
const double minGS = 0;
const double maxGS = 60;
